# Generated by Django 3.2.5 on 2021-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=10)),
                ('clean_tweets', models.TextField()),
            ],
        ),
    ]
